const NODE_PORT = process.env.NODE_PORT;
const DATABASE_NAME = process.env.DATABASE_NAME;
const DATABASE_USER = process.env.DATABASE_USER;
const DATABASE_USER_PASSWORD = process.env.DATABASE_USER_PASSWORD;
const DATABASE_HOST= process.env.DATABASE_HOST;
const DATABASE_PORT = process.env.DATABASE_PORT;
const DATABASE_MAX_CONNECTION_POOL = process.env.DATABASE_MAX_CONNECTION_POOL;

export {
  NODE_PORT,
  DATABASE_NAME,
  DATABASE_USER,
  DATABASE_USER_PASSWORD,
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_MAX_CONNECTION_POOL
}